INSERT INTO admin(name,password) VALUES('Admin','$2a$10$QLtK4FF/l3SQhKko8EyTSOr6HqSH/OVBszlm4EE1HuYUY46kF.zru');
INSERT INTO team(name,coach,country,password) VALUES('Fast Footers','Ram','India','$2a$10$DELjnx75NUTLY1OQp8LLU.XoJ1OtGoariu2gcFtlD3ZFhAv5y2TBi');
INSERT INTO team(name,coach,country,password) VALUES('Fire Fighters','Karthick','America','$2a$10$XLQqMVB7J3mfwx992yG7lekvliASmk2p5v.a89asfAm2MpKTEav1a');
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Jeje',29,171,59,'Forwarder',true,1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Stiven Mendoza',32,211,89,'Forwarder',true,1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Dhanachandra Singh',26,136,51,'Defender',true,1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Abhishek Das', 35, 115, 18, 'Defender', true, 1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('MaÃ­lson Alves', 28, 165, 24, 'Defender', true, 1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Jerry Lalrinzuala', 36, 111, 14, 'Defender', true, 1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Laldinliana Renthlei', 23, 76, 9, 'Defender', true, 1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Elano', 30, 167, 67, 'Mid-Fielder', true, 1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Bruno Pelissari', 29, 115, 46, 'Mid-Fielder', true, 1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Dhanpal Ganesh', 23, 89, 34, 'Mid-Fielder', true, 1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Karanjit Singh', 32, 189, 14, 'Goal Keeper', true, 1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Karthick', 31, 201, 87, 'Forwarder', false, 1);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Neymar', 29, 161, 88, 'Forwarder', true, 2);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Dani Alves', 35, 221, 52, 'Mid-Fielder', true, 2);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Tiago Silva', 34, 141, 21, 'Defender', true, 2);
INSERT INTO player(name,age,no_of_matches,goals_scored,type,in_eleven,players) VALUES('Ivan Quarasma Da Silva', 22, 54, 3, 'Goal Keeper', false, 2);
INSERT INTO mapping(name,category) VALUES('', 'Semi-Final 1');
INSERT INTO mapping(name,category) VALUES('', 'Semi-Final 2');
INSERT INTO mapping(name,category) VALUES('', 'Final');
INSERT INTO mapping(name,category) VALUES('', 'Team 1');
INSERT INTO mapping(name,category) VALUES('', 'Team 2');
INSERT INTO mapping(name,category) VALUES('', 'Team 3');
INSERT INTO mapping(name,category) VALUES('', 'Team 4');
